name: DevSkim-validate
on: [workflow_dispatch]
jobs:
  DevSkim-validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: wget https://github.com/microsoft/DevSkim/releases/download/v1.0.33/DevSkim_CLI_linux_1.0.33.zip
    - run: unzip DevSkim_CLI_linux_1.0.33.zip
    - run: ls -al
